### ISSUE TITLE
Can't verify the part 3 results since inputs are missing

### ISSUE THREAD

**Issue by wcn3** [NotCamelCase/RasterizationInOneWeekend#1]
The sponza.obj and cubes.obj files are missing from the repo.

The .gitignore in the repo drops .obj files since they look like outputs from the compiler, but in this case, these .obj files are graphics entities that need to be added.

Can you please fix the repo to include these files so I can keep going? I've enjoyed working through this so far.

**Comment by NotCamelCase** [comment]
Hi, thanks for pointing that out. You're right, not having checked out the files is an issue. I'll try to work it out.

**Comment by NotCamelCase** [comment]
I uploaded missing .OBJ files, please try this: https://github.com/NotCamelCase/RasterizationInOneWeekend/commit/e0d27eac46d8c408de0ff88bb08bd8787ed3e371

Thanks again!
